### ISSUE TITLE
Uncaught Exception: at validateState

### ISSUE THREAD

**Issue by JsseL** [mawie81/electron-window-state#19]
Tried to restart my application and during `windowStateKeeper` initialization this library threw unhandled exception.

**Traceback:**
```
Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from # <Object>
    at TypeError (native)
    at validateState
(D:\projects\my_app\app\app\node_modules\electron-window-state\index.js:45:34)
    at module.exports
(D:\projects\my_app\app\app\node_modules\electron-window-state\index.js:153:3)
...
rest of the traceback is from my app (not relevant)
```

**My code**
```
        const mainWindowState = windowStateKeeper({
            defaultWidth: 1200,
            defaultHeight: 800,
        });
        const {x, y} = mainWindowState;
        const validLocation = isValidScreenLocation(x, y);  // Custom function to validate x and y positions
        const mainWindow = this.mainWindow = new BrowserWindow({
            x: validLocation ? x : 100,  // Default to 100 when no valid screen location
            y: validLocation ? y : 100,  // Default to 100 when no valid screen location
            width: mainWindowState.width,
            height: mainWindowState.height,
        });
```

**Contents of my stored window-state.json**
```
{
  "width": 1200,
  "height": 768,
  "x": 100,
  "y": 100,
  "isMaximized": false,
  "isFullScreen": false,
  "displayBounds": {
    "x": 0,
    "y": 0,
    "width": 1366,
    "height": 768
  }
}
```

Didn't figure out yet what was the actual problem.

**I'm using:**
- electron-window-state: 4.0.1
- electron: 1.4.2

**Comment by JsseL** [comment]
After debugging a bit more, I found out that the `window-state.json` I was looking at was actually wrong file. Correct file was not the one in `C:\Users\me\AppData\Roaming\myapp`, instead the file in `C:\Users\me\AppData\Roaming\Electron` was used.

The file in `C:\Users\me\AppData\Roaming\Electron` looks like this:
```
{
  "width": 1304,
  "height": 768,
  "x": null,
  "y": 118,
  "isMaximized": true,
  "isFullScreen": false,
  "displayBounds": {
    "x": 0,
    "y": 0,
    "width": 1366,
    "height": 768
  }
}
```

And now the problem makes sense. The problem is most likely caused by `"x": null,`. Still not sure how `null` ends up in there.

**Improvement ideas**
1. We could have decent defaults during state update. Something like `state.x = winBounds.x || 0;` in `updateState` function.
2. We could validate state before saving it. That way we could be fairly sure that anything that gets saved is actually valid.
3. After everything goes bad we could at least use some safe defaults. Current implementation totally disables the whole application start up at the moment for me. Removing any invalid state file and using safe defaults would be much nicer.

Anyways, really nice library. Thanks for maintaining it!

**Comment by mawie81** [comment]
Thanks for looking into this. 👍  
Will try to come up with a solution for this.
Validating before save and falling back to defaults in case something is strange seems a good idea. The same applies for validating the loaded state.
