### ISSUE TITLE
if (state.x > displayBounds.width) {  correct?

### ISSUE THREAD

**Issue by greggman** [mawie81/electron-window-state#31]
https://github.com/mawie81/electron-window-state/blob/e76fe1e006af5eb496e7f66194f3eaadcf4bfc77/index.js#L49

Just curious how `state.x` can be compared to `displayBounds.width`.  state.x is not related to `displayBounds.width`. Maybe you meant to compare it to right as in `displayBounds.x + displayBounds.width`? 

Or maybe I'm just not understanding the logic.

**Comment by mawie81** [comment]
@M1kep is correct 😃

**Comment by greggman** [comment]
If the user has than one display this check is invalid

**Comment by M1kep** [comment]
It looks like screen is defined by the electron screen. I'm not positive right now, but I believe that is the current screen the app is on. And display bounds is based on that screen object.

**Comment by greggman** [comment]
not sure what you mean. The display bounds are defined by x, y, width and height. Checking my two monitors via electron I see one has a bound.x of -1440

**Comment by greggman** [comment]
note if you don't have 2 monitors but you have an Apple TV (or Android TV running an AirPlay app) you can use that as a second monitor

**Comment by greggman** [comment]
If I'm not being clear, Imaging you have 2 monitors. One is right of the other. The bounds for the 2 monitors are

    x: 0, y: 0, width: 1000, height: 500
    x: 1000, y: 0, width: 1000, height: 500

If `displayBounds = screen.getDisplayMatching(state).bounds;` returns the second monitor then state.x will >= 1000 so the test `state.x > displayBounds.width` will fail even though you want it to pass. It seems like the correct test is `state.x > displayBounds.x + displayBounds.width`?
