### ISSUE TITLE
Window state saved when second screen disconnected

### ISSUE THREAD

**Issue by rschuetzler** [mawie81/electron-window-state#43]
I sometimes use a second monitor, and sometimes I don't. If an app has `window-state.json` stored with a location on the second monitor, then the second monitor is disconnected, I cannot see the app when the app is launched again. It is launched off the screen, and the only way I can figure to bring it back is to delete `window-state.json`. Using Win+left doesn't move it, it just stays there.

**Comment by mawie81** [comment]
See #44
