### ISSUE TITLE
App launched outside display area when second screen disconnected

### ISSUE THREAD

**Issue by MathieuDebit** [mawie81/electron-window-state#44]
## About
This bug has a reproduction step on Windows 10.
Mac OSX is also affected but seems to automatically correct wrong display positioning.
No clear info on Linux.

I know this issue was reported in multiple issues but this one tends to gather everything necessary to fix it.

Related: https://github.com/mawie81/electron-window-state/issues/1, https://github.com/mawie81/electron-window-state/issues/4, https://github.com/mawie81/electron-window-state/issues/27, https://github.com/mawie81/electron-window-state/issues/31, https://github.com/mawie81/electron-window-state/issues/38, https://github.com/mawie81/electron-window-state/issues/43.

## Reproduction Steps
Here is a repo to reproduce the bug: https://github.com/MathieuDebit/electron-quick-start/pull/3

**Comment by gseregni** [comment]
Same here..

**Comment by MathieuDebit** [comment]
The algorithm that checks if the window can be displayed within display bounds is in the validateState() method:

https://github.com/mawie81/electron-window-state/blob/6bb0a3f175bc5bc9ddf8bf5cace3aa8cdc9b4a46/index.js#L45-L69

Here is an explanation of what this is doing:

- Retrieve the display that most closely intersects the saved bounds, and get its bounds
- if the retrieved bounds is not deeply equal to the saved bounds:
  - if the retrieved screen size is smaller than the saved screen size:
    - if the saved window position values are bigger than the retrieved screen size:
      - set the window position values to 0
    - if the saved window size is bigger than the retrieved screen size:
      - set the window size to the retrieved screen size

This logic has drawbacks because it only takes into accounts positive values. Therefore it only works with this exact dual screen setup (with the window previously positioned in the second screen which is bigger than the primary one):

![capture](https://user-images.githubusercontent.com/6206650/48432676-5bac2b80-e775-11e8-8cbf-0896a8b55cb1.PNG)

**Comment by MathieuDebit** [comment]
Mac OSX is handling the window positioning differently than Windows. This difference can be simply tested by manually setting the main window position in a basic [electron-quick-start](https://github.com/electron/electron-quick-start) example.

With these options:
```javascript
mainWindow = new BrowserWindow({
    'x': -100,
    'y': 0,
    'width': 800,
    'height': 600,
  });
```

the window in Windows will be 100px off the main screen and partly in the second screen, while on Mac OSX the window will be fully on the main screen. You can't position a window between two screens in OSX.
We can understand that Windows has an extended desktop while Mac OSX has separate ones.

Actually `electron-boilerplate` checks if the window is within a display bounds. See [electron-boilerplate:src/helpers/window.js](https://github.com/szwacz/electron-boilerplate/blob/bd4812720b0bd5f21beb413e567723bae653d5f5/src/helpers/window.js#L58-L68).

**Comment by mawie81** [comment]
With the merge of #45 this issue is hopefully fixed 👍 
Thx @MathieuDebit
